version: '3.8'

services:
  planka-db:
    image: postgres:14-alpine
    container_name: planka-db
    restart: unless-stopped
    volumes:
      - planka-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planka
      POSTGRES_USER: planka
      POSTGRES_PASSWORD: planka
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planka"]
      interval: 10s
      timeout: 5s
      retries: 5

  planka-app:
    build: .
    container_name: planka-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      planka-db:
        condition: service_healthy
    environment:
      BASE_URL: https://planka-1.onrender.com
      DATABASE_URL: postgresql://neondb_owner:npg_r7JZXHo8VQcx@ep-green-surf-adgtxz2z-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      SECRET_KEY: MySuperSecretKey123456789
      TOKEN_EXPIRES_IN: 365
      PORT: 3000
      # Optional: Default admin user (created on first run)
      DEFAULT_ADMIN_EMAIL: demo@demo.demo
      DEFAULT_ADMIN_PASSWORD: demo
      DEFAULT_ADMIN_NAME: Demo Admin
      DEFAULT_ADMIN_USERNAME: demo
    volumes:
      - planka-user-avatars:/app/public/user-avatars
      - planka-background-images:/app/public/background-images
      - planka-attachments:/app/private/attachments

volumes:
  planka-db-data:
  planka-user-avatars:
  planka-background-images:
  planka-attachments:
